name: Call APIs

on:
  push:
    branches:
      - main
      - prod

jobs:
  call-api-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Call API for main
        run: |
          response=$(curl -s -X GET https://flow.sokt.io/func/scriESGNpMOS)
          echo "Response from Dev API: $response"

  call-api-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Call API for Prod
        run: |
          response=$(curl -s -X GET https://httpbin.org/get)
          echo "Response from Prod API: $response"
