name: Call APIs on Branch Push

on:
  push:
    branches:
      - dev
      - prod

jobs:
  call-api-on-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Call API on dev Branch
        run: |
          response=$(curl -s -X GET https://httpbin.org/get)
          echo "Response from API on dev branch: $response"
          echo ${{ toJson(github) }}

  call-api-on-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Call API on prod Branch
        run: |
          response=$(curl -s -X GET https://flow.sokt.io/func/scriESGNpMOS?key)
          echo "Response from API on prod branch: $response"
